import path from "node:path";
import type { Page } from "@playwright/test";
import { expect } from "@playwright/test";

/** `examples/` lives at the repo root, three levels up from `apps/web/e2e/`. */
export const EXAMPLES_DIR = path.resolve(__dirname, "../../../examples");

/**
 * The local Supabase stack's email catcher (Mailpit — `[local_smtp]` in
 * supabase/config.toml, DECISIONS.md §14d). Every OTP email the passwordless
 * flow "sends" locally lands here instead of being really delivered, and its
 * REST API is how these tests read the real 6-digit code — the same code a
 * human would read out of the web UI on this port. Nothing is mocked: the
 * code was generated by the real GoTrue server and is verified against it.
 */
export const MAILPIT_URL = "http://127.0.0.1:55324";

/** A unique-per-run email so parallel/repeated runs never collide between mailboxes. */
export function uniqueEmail(label: string): string {
  return `e2e-${label}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}@example.test`;
}

/** How many OTP emails Mailpit currently holds for this address. */
export async function countOtpEmails(email: string): Promise<number> {
  const res = await fetch(`${MAILPIT_URL}/api/v1/search?query=${encodeURIComponent(`to:"${email}"`)}`);
  if (!res.ok) {
    throw new Error(`Mailpit search failed (${res.status}) — is the local Supabase stack running with [local_smtp] enabled?`);
  }
  const body = (await res.json()) as { messages_count: number };
  return body.messages_count;
}

/**
 * Polls Mailpit until a *new* OTP email (beyond `previousCount`) exists for
 * this address, then extracts the real 6-digit code from the newest
 * message's full text body.
 */
export async function waitForOtpCode(email: string, previousCount = 0, timeoutMs = 15_000): Promise<string> {
  const deadline = Date.now() + timeoutMs;
  const query = encodeURIComponent(`to:"${email}"`);

  while (Date.now() < deadline) {
    const res = await fetch(`${MAILPIT_URL}/api/v1/search?query=${query}`);
    if (res.ok) {
      const body = (await res.json()) as { messages_count: number; messages: Array<{ ID: string }> };
      if (body.messages_count > previousCount && body.messages.length > 0) {
        // Search results are newest-first; read the full body of the newest.
        const detail = await fetch(`${MAILPIT_URL}/api/v1/message/${body.messages[0].ID}`);
        const message = (await detail.json()) as { Text: string };
        const match = message.Text.match(/\b(\d{6})\b/);
        if (!match) {
          throw new Error(`OTP email for ${email} arrived but contained no 6-digit code:\n${message.Text}`);
        }
        return match[1];
      }
    }
    await new Promise((r) => setTimeout(r, 250));
  }

  throw new Error(`Timed out waiting for an OTP email to ${email} (had ${previousCount} before)`);
}

/** The PIN input on the code step (shadcn `input-otp` renders one real textbox). */
export function otpInput(page: Page) {
  return page.getByRole("textbox", { name: "6-digit code" });
}

/**
 * Drives the real passwordless sign-in flow end to end (DECISIONS.md §14d):
 * request a code from the single /login screen, read the actual 6-digit
 * code GoTrue emailed from the local Mailpit catcher, enter it into the PIN
 * input, and land authenticated on /dashboard. First-time emails create the
 * account transparently (`shouldCreateUser` default) — there is no separate
 * signup flow anymore, so this one helper covers both "new" and "returning"
 * users identically.
 */
export async function signIn(page: Page, email: string): Promise<void> {
  await page.goto("/login");
  await page.getByLabel("Email").fill(email);
  const alreadySent = await countOtpEmails(email);

  // GoTrue enforces a same-address send-frequency guard (`max_frequency`,
  // 1s locally) — a spec that signs the same address in twice back-to-back
  // (e.g. the sign-out -> sign-back-in test) can legitimately trip it,
  // because the whole local flow completes in under a second. Waiting it
  // out and retrying exercises the app's real error handling rather than
  // weakening the guard.
  const codeHeading = page.getByRole("heading", { name: "Check your email", level: 1 });
  for (let attempt = 0; attempt < 3; attempt++) {
    await page.getByRole("button", { name: "Send code" }).click();
    const throttled = page.getByText("Too many attempts");
    await expect(codeHeading.or(throttled).first()).toBeVisible();
    if (await codeHeading.isVisible()) break;
    await page.waitForTimeout(1200);
  }
  await expect(codeHeading).toBeVisible();

  const code = await waitForOtpCode(email, alreadySent);
  // Filling all 6 digits triggers the input's onComplete auto-verify.
  await otpInput(page).fill(code);

  await page.waitForURL("**/dashboard");
  // Card titles in this UI (apps/web/src/components/ui/card.tsx's CardTitle)
  // render as plain <div>s, not semantic headings — matched by text here.
  await expect(page.getByText("Upload a log file", { exact: true })).toBeVisible();
}
